version: 2

project_name: captainbi-cli

builds:
  - id: cbi
    main: .
    binary: cbi
    goos: [darwin, linux, windows]
    goarch: [amd64, arm64]
    flags:
      - -buildvcs=false
    ldflags:
      - "-s -w -X github.com/kirkzwy/captainbi-cli/cmd.version={{ .Version }}"

archives:
  - id: default
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - README.md
      - LICENSE

checksum:
  name_template: "checksums.txt"

snapshot:
  version_template: "{{ incpatch .Version }}-next"
